### ISSUE TITLE
fatal error: coin/IpTNLP.hpp: No such file or directory

### ISSUE THREAD

**Issue by takeoffstd** [HeechanShin/KinodynamicComfortTrajectoryPlanning#1]
Hi Heechanhin,
    I want to run your ComfortTrajectoryPlanning package. When I catkin_make the whole package, there is an error 
/catkin_ws1/src/KinodynamicComfortTrajectoryPlanning/include/ComfortOptimizer.h:8:27: fatal error: coin/IpTNLP.hpp: No such file or directory
could you provide the whole package, I am grateful to learn your ComfortTrajectoryPlanning!

Thank you

**Comment by HeechanShin** [comment]
Thanks to have an interest in my work!
That error occurs due to the library, IPOPT.
You can easily download it by using coinbrew ( please see https://github.com/coin-or/Ipopt for more detail!).
Since it is quite a heavy library, it may hard to provide as a whole package.
